### ISSUE TITLE
"<" and ">" characters get stripped from the input text

### ISSUE THREAD

**Issue by fitzgen** [msurguy/cnc-text-tool#6]
### Steps to reproduce:

* upload `empty.svg` into the tool

  <details>
  
  <summary><code>empty.svg</code></summary>

  ```svg
  <svg xmlns="http://www.w3.org/2000/svg">
  </svg>
  ```

  </details>

* type `Uniform<i64>` into the input text box

* download the resulting svg

### Expected results:

The downloaded SVG has the text with its `<` and `>` characters: `Uniform<i64>`

### Actual results:

The downloaded SVG has the text without the `<` and `>` characters: `Uniformi64`

----------

Thanks for making this tool!

**Comment by msurguy** [comment]
@fitzgen I haven't been able to reproduce this, maybe I did fix it a while ago but didn't test at the time. 

Can you let me know if everything works as expected now? 

Thanks!

**Comment by fitzgen** [comment]
Yep, it appears to be fixed now! Thanks!
